blank_issues_enabled: false
contact_links:
  - name: YeeHaw Circuits
    url: mailto:yeehawcircuits@gmail.com
    about: Having trouble getting the motor driver to work? Send an email or post an Issue!
